import React,{useEffect,useState} from 'react';
import api from '../services/api';
import {inventoryApi,settingsApi} from '../services/businessApi';
import './Pages.css';
const n=(v:any)=>Number(v)||0;
const Dashboard:React.FC=()=>{
 const [tiles,setTiles]=useState<any[]>([]),[raw,setRaw]=useState<any[]>([]),[pack,setPack]=useState<any[]>([]),[finished,setFinished]=useState<any[]>([]),[bookings,setBookings]=useState<any[]>([]),[invoices,setInvoices]=useState<any[]>([]),[maintenance,setMaintenance]=useState<any[]>([]);
 useEffect(()=>{Promise.all([settingsApi.getDashboardTiles(),inventoryApi.rawSummary(),inventoryApi.packagingSummary(),inventoryApi.finishedSummary(),api.get('/bookings'),api.get('/invoices'),api.get('/maintenance')]).then(([t,r,p,f,b,i,m])=>{setTiles((t.data?.data||[]).filter((x:any)=>x.active&&x.visible).sort((a:any,b:any)=>a.sortOrder-b.sortOrder));setRaw(r.data?.data||[]);setPack(p.data?.data||[]);setFinished(f.data?.data||[]);setBookings(b.data?.data?.bookings||b.data?.data||[]);setInvoices(i.data?.data||[]);setMaintenance(m.data?.data?.records||[]);}).catch(()=>{});},[]);
 const value=(code:string)=>{if(code==='RAW_OIL_STOCK')return raw.reduce((s,x)=>s+n(x.totalAvailableQuantity),0).toLocaleString('en-IN');if(code==='PACKAGING_STOCK')return pack.reduce((s,x)=>s+n(x.availableQuantity),0).toLocaleString('en-IN');if(code==='FINISHED_GOODS_STOCK')return finished.reduce((s,x)=>s+n(x.totalAvailableQuantity),0).toLocaleString('en-IN');if(code==='PENDING_BOOKINGS')return bookings.filter((x:any)=>!['COMPLETED','CANCELLED'].includes(String(x.status||x.bookingstatus).toUpperCase())).length;if(code==='DRAFT_INVOICES')return invoices.filter((x:any)=>x.status==='DRAFT').length;if(code==='MAINTENANCE_LOSS')return maintenance.filter((x:any)=>x.status==='ACTIVE').length;return '-';};
 return <div className="dashboard"><div className="dashboard-header"><h1>Dashboard</h1><p>Operational summary from inventory, bookings, invoices and maintenance</p></div><div className="dashboard-stats">{tiles.map(t=><div className="stat-card" key={t.id||t.code}><div className="stat-content"><h3>{t.label}</h3><div className="stat-value">{value(t.code)}</div><div className="stat-subtext">Configured in Application Settings</div></div></div>)}</div></div>;
};export default Dashboard;
