import React,{useEffect,useState} from 'react';
import {inventoryApi} from '../services/businessApi';
import './Pages.css';
const n=(v:any)=>Number(v)||0;
const money=(v:any)=>`₹${n(v).toLocaleString('en-IN',{maximumFractionDigits:2})}`;
const Inventory:React.FC=()=>{
 const [tab,setTab]=useState<'raw'|'packaging'|'finished'>('raw');const [raw,setRaw]=useState<any[]>([]),[pack,setPack]=useState<any[]>([]),[finished,setFinished]=useState<any[]>([]),[error,setError]=useState('');
 const load=async()=>{try{const [a,b,c]=await Promise.all([inventoryApi.rawSummary(),inventoryApi.packagingSummary(),inventoryApi.finishedSummary()]);setRaw((a.data?.data||[]) as any[]);setPack((b.data?.data||[]) as any[]);setFinished((c.data?.data||[]) as any[]);}catch{setError('Failed to load inventory');}};useEffect(()=>{load();},[]);
 const card=(title:string,lines:React.ReactNode[])=><div className="summary-card" style={{minWidth:280,padding:0,overflow:'hidden'}}><div style={{background:'#3498db',color:'#fff',padding:'20px',fontSize:22,fontWeight:700,textAlign:'center'}}>{title}</div><div style={{padding:22}}>{lines.map((l,i)=><div key={i} style={{padding:'12px 0',borderBottom:i<lines.length-1?'1px solid #edf0f2':'none'}}>{l}</div>)}</div></div>;
 return <div className="module-page"><div className="module-header"><div><h1>Inventory Management</h1><p>Monitor raw materials, packaging, and finished goods inventory</p></div></div>{error&&<div className="error-message">{error}</div>}
 <div style={{display:'flex',gap:12,borderBottom:'1px solid #ddd',paddingBottom:14,marginBottom:24}}>{[['raw','Raw Oil Inventory'],['packaging','Packaging Summary'],['finished','Finished Goods']].map(([k,l])=><button key={k} className={tab===k?'primary-button':'secondary-button'} onClick={()=>setTab(k as any)}>{l}</button>)}</div>
 {tab==='raw'&&<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(300px,1fr))',gap:22}}>{raw.map(x=>card(String(x.oilType||'Oil').replace(/_/g,' '),[<><b>Total Batches:</b> <span style={{float:'right'}}>{x.totalBatches}</span></>,<><b>Total Quantity:</b> <span style={{float:'right'}}>{n(x.totalAvailableQuantity).toLocaleString('en-IN')}</span></>,<><b>Last Purchase Avg Cost:</b> <span style={{float:'right',color:'#20ad63',fontWeight:700}}>{money(x.lastPurchaseAverageCost)}</span></>,<><b>Recent Batch:</b> <span style={{float:'right'}}>{x.recentPurchaseBatchNumber||'-'}</span></>,<><b>Recent Batch Remaining:</b> <span style={{float:'right'}}>{n(x.recentBatchRemainingQuantity).toLocaleString('en-IN')}</span></>]))}</div>}
 {tab==='packaging'&&<div style={{overflowX:'auto'}}><table className="data-table"><thead><tr><th>Material</th><th>Subtype</th><th>Available</th><th>Unit</th><th>Last Purchase Avg Cost</th><th>Recent Batch</th><th>Recent Remaining</th></tr></thead><tbody>{pack.map((x,i)=><tr key={i}><td>{x.materialVariant||x.materialType}</td><td>{x.subtypeLabel||'-'}</td><td>{n(x.availableQuantity).toLocaleString('en-IN')}</td><td>{x.stockUnit}</td><td>{money(x.lastPurchaseAverageCost)}</td><td>{x.recentPurchaseBatchNumber||'-'}</td><td>{n(x.recentBatchRemainingQuantity).toLocaleString('en-IN')}</td></tr>)}</tbody></table></div>}
 {tab==='finished'&&<div style={{overflowX:'auto'}}><table className="data-table"><thead><tr><th>Product Type</th><th>Produced</th><th>Available</th><th>Sold</th><th>Good Returned</th><th>Defective Returned</th><th>Recent Batch</th></tr></thead><tbody>{finished.map((x,i)=><tr key={x.productTypeId||i}><td>{x.productLabel}</td><td>{n(x.totalProducedQuantity)}</td><td style={{fontWeight:700,color:'#20ad63'}}>{n(x.totalAvailableQuantity)}</td><td>{n(x.totalSoldQuantity)}</td><td>{n(x.totalGoodReturnedQuantity)}</td><td>{n(x.totalDefectiveReturnedQuantity)}</td><td>{x.recentBatchNumber||'-'}</td></tr>)}</tbody></table></div>}
 </div>;
};export default Inventory;
