import React,{useEffect,useMemo,useState} from 'react';
import {maintenanceApi} from '../services/businessApi';
import './Pages.css';
const today=()=>new Date().toISOString().slice(0,10); const n=(v:any)=>Number(v)||0;
const Maintenance:React.FC=()=>{
 const [types,setTypes]=useState<any[]>([]),[records,setRecords]=useState<any[]>([]),[inventory,setInventory]=useState<any[]>([]),[show,setShow]=useState(false),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 const [form,setForm]=useState<any>({maintenanceTypeId:'',maintenanceSubtypeId:'',transactionDate:today(),amount:'',quantity:'',rawOilInventoryId:'',packagingInventoryId:'',finishedGoodsInventoryId:'',finishedProductTypeId:'',additionalNotes:'',attachment:null});
 const load=async()=>{const [c,l]=await Promise.all([maintenanceApi.configuration(),maintenanceApi.list()]);setTypes(c.data?.data||[]);setRecords(l.data?.data?.records||[]);};useEffect(()=>{load().catch(()=>setError('Failed to load maintenance'));},[]);
 const type=useMemo(()=>types.find(x=>x.id===form.maintenanceTypeId||x.code===form.maintenanceTypeId),[types,form.maintenanceTypeId]); const subs=(type?.subtypes||[]).filter((x:any)=>x.active); const sub=useMemo(()=>subs.find((x:any)=>x.id===form.maintenanceSubtypeId||x.code===form.maintenanceSubtypeId),[subs,form.maintenanceSubtypeId]);
 useEffect(()=>{setInventory([]);setForm((f:any)=>({...f,rawOilInventoryId:'',packagingInventoryId:'',finishedGoodsInventoryId:'',finishedProductTypeId:'',quantity:'',amount:''}));if(sub?.inventoryType&&sub.inventoryType!=='NONE')maintenanceApi.inventoryOptions(sub.inventoryType).then(r=>setInventory(r.data?.data||[])).catch(()=>setInventory([]));},[form.maintenanceSubtypeId]);
 const inventoryId=sub?.inventoryType==='RAW_OIL'?form.rawOilInventoryId:sub?.inventoryType==='PACKAGING'?form.packagingInventoryId:form.finishedGoodsInventoryId; const selected=inventory.find(x=>x._id===inventoryId);
 const save=async()=>{setError('');if(!type||!sub){setError('Main Type and Subtype are required');return;}const fd=new FormData();Object.keys(form).forEach(k=>{if(k==='attachment'){if(form.attachment)fd.append('attachment',form.attachment);return;}if(form[k]!==''&&form[k]!==null)fd.append(k,String(form[k]));});if(sub.inventoryType==='FINISHED_GOOD'&&selected)fd.set('finishedProductTypeId',String(selected.productTypeId||''));setSaving(true);try{await maintenanceApi.create(fd);setShow(false);setForm({maintenanceTypeId:'',maintenanceSubtypeId:'',transactionDate:today(),amount:'',quantity:'',rawOilInventoryId:'',packagingInventoryId:'',finishedGoodsInventoryId:'',finishedProductTypeId:'',additionalNotes:'',attachment:null});await load();}catch(e:any){setError(e?.error?.message||'Failed to save maintenance entry');}finally{setSaving(false);}};
 const reverse=async(id:string)=>{const reason=window.prompt('Reason for reversal?');if(!reason)return;try{await maintenanceApi.reverse(id,reason);await load();}catch(e:any){setError(e?.error?.message||'Failed to reverse entry');}};
 return <div className="module-page"><div className="module-header"><div><h1>Maintenance & Expenses</h1><p>Record inventory losses, damage, services and operating expenses</p></div><button className="primary-button" onClick={()=>setShow(true)}>+ Add Entry</button></div>{error&&<div className="error-message">{error}</div>}
 <div style={{overflowX:'auto'}}><table className="data-table"><thead><tr><th>Date</th><th>Main Type</th><th>Subtype</th><th>Item</th><th>Batch</th><th>Qty</th><th>Amount</th><th>Status</th><th>Action</th></tr></thead><tbody>{records.map(r=><tr key={r._id}><td>{new Date(r.transactionDate).toLocaleDateString()}</td><td>{r.maintenanceTypeLabel}</td><td>{r.maintenanceSubtypeLabel}</td><td>{r.oilType||r.packagingType||r.finishedProductLabel||'-'}</td><td>{r.batchNumber||'-'}</td><td>{r.quantity??'-'} {r.unit||''}</td><td>{r.amount!=null?`₹${n(r.amount).toLocaleString('en-IN')}`:'-'}</td><td>{r.status}</td><td>{r.status==='ACTIVE'&&<button className="secondary-button" onClick={()=>reverse(r._id)}>Reverse</button>}</td></tr>)}</tbody></table></div>
 {show&&<div className="modal"><div className="modal-content"><div className="modal-header"><h3>Add Maintenance / Expense Entry</h3><button className="modal-close" onClick={()=>setShow(false)}>×</button></div><div className="form-grid">
 <div className="form-group"><label>Main Type *</label><select value={form.maintenanceTypeId} onChange={e=>setForm({...form,maintenanceTypeId:e.target.value,maintenanceSubtypeId:''})}><option value="">-- Select --</option>{types.map(t=><option key={t.id} value={t.id}>{t.label}</option>)}</select></div>
 <div className="form-group"><label>Subtype *</label><select value={form.maintenanceSubtypeId} onChange={e=>setForm({...form,maintenanceSubtypeId:e.target.value})} disabled={!type}><option value="">-- Select --</option>{subs.map((s:any)=><option key={s.id} value={s.id}>{s.label}</option>)}</select></div>
 <div className="form-group"><label>Date *</label><input type="date" value={form.transactionDate} onChange={e=>setForm({...form,transactionDate:e.target.value})}/></div>
 {sub?.inventoryType==='RAW_OIL'&&<div className="form-group"><label>Oil Type / Batch *</label><select value={form.rawOilInventoryId} onChange={e=>setForm({...form,rawOilInventoryId:e.target.value})}><option value="">-- Select --</option>{inventory.map(x=><option key={x._id} value={x._id}>{x.oilType} — {x.batchNumber} — {n(x.availableQuantity)} {x.inventoryUnit}</option>)}</select></div>}
 {sub?.inventoryType==='PACKAGING'&&<div className="form-group"><label>Packaging Type *</label><select value={form.packagingInventoryId} onChange={e=>setForm({...form,packagingInventoryId:e.target.value})}><option value="">-- Select --</option>{inventory.map(x=><option key={x._id} value={x._id}>{x.materialVariant}{x.subtypeLabel?` - ${x.subtypeLabel}`:''} — {n(x.availableQuantity)} {x.inventoryUnit}</option>)}</select></div>}
 {sub?.inventoryType==='FINISHED_GOOD'&&<div className="form-group"><label>Finished Good / Batch *</label><select value={form.finishedGoodsInventoryId} onChange={e=>setForm({...form,finishedGoodsInventoryId:e.target.value})}><option value="">-- Select --</option>{inventory.map(x=><option key={x._id} value={x._id}>{x.productLabel} — {x.batchNumber} — {n(x.availableQuantity)} available</option>)}</select></div>}
 {sub?.quantityRequired&&<div className="form-group"><label>Quantity *</label><input type="number" min="0" max={selected?.availableQuantity||undefined} value={form.quantity} onChange={e=>setForm({...form,quantity:e.target.value})}/>{selected&&<small>Available: {selected.availableQuantity} {selected.inventoryUnit||'PCS'}</small>}</div>}
 {(sub?.amountRequired||sub?.entryBehavior==='INVENTORY_AND_EXPENSE')&&<div className="form-group"><label>Amount {sub?.amountRequired?'*':''}</label><input type="number" min="0" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></div>}
 <div className="form-group"><label>Attachment</label><input type="file" accept="image/png,image/jpeg,application/pdf" onChange={e=>setForm({...form,attachment:e.target.files?.[0]||null})}/></div>
 <div className="form-group" style={{gridColumn:'1/-1'}}><label>Additional Notes</label><textarea rows={3} value={form.additionalNotes} onChange={e=>setForm({...form,additionalNotes:e.target.value})}/></div>
 </div><div className="modal-actions"><button className="primary-button" disabled={saving} onClick={save}>{saving?'Saving...':'Save Entry'}</button><button className="secondary-button" onClick={()=>setShow(false)}>Cancel</button></div></div></div>}
 </div>;
};export default Maintenance;
