import React,{useEffect,useMemo,useState} from 'react';
import {batchApi} from '../services/businessApi';
import './Pages.css';
const n=(v:any)=>Number(v)||0;
const OilBatchProcessing:React.FC=()=>{
 const [rows,setRows]=useState<any[]>([]),[opts,setOpts]=useState<any>({oilTypes:[],sourceBatches:[],productProfiles:[]}),[show,setShow]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const [form,setForm]=useState<any>({oilType:'',batchNumber:'',productTypeId:'',quantity:0}); const [cap,setCap]=useState<any>(null);
 const load=async()=>{const [a,b]=await Promise.all([batchApi.list(),batchApi.options()]);setRows(a.data?.data?.batches||[]);setOpts(b.data?.data||{});}; useEffect(()=>{load().catch(()=>setError('Failed to load batch data'));},[]);
 const batches=useMemo(()=>opts.sourceBatches?.filter((x:any)=>x.oilType===form.oilType&&n(x.availableQuantity)>0)||[],[opts,form.oilType]);
 const products=useMemo(()=>opts.productProfiles?.filter((x:any)=>!x.oilType||x.oilType===form.oilType)||[],[opts,form.oilType]);
 useEffect(()=>{setCap(null); if(form.oilType&&form.batchNumber&&form.productTypeId) batchApi.capacity(form).then(r=>setCap(r.data?.data||null)).catch(()=>setCap(null));},[form.oilType,form.batchNumber,form.productTypeId]);
 const create=async()=>{setError('');if(!form.oilType||!form.batchNumber||!form.productTypeId||n(form.quantity)<=0){setError('Oil Type, Batch Number, Product Type and Quantity are required');return;}if(cap&&n(form.quantity)>n(cap.calculatedMaxQuantity)){setError(`Maximum producible quantity is ${cap.calculatedMaxQuantity}`);return;}setLoading(true);try{await batchApi.create({...form,quantity:n(form.quantity)});setShow(false);setForm({oilType:'',batchNumber:'',productTypeId:'',quantity:0});setCap(null);await load();}catch(e:any){setError(e?.error?.message||'Failed to create batch');}finally{setLoading(false);}};
 return <div className="module-page"><div className="module-header"><div><h1>Oil Batch Processing</h1><p>Create finished goods using active tanker batches and available primary packaging</p></div><button className="primary-button" onClick={()=>setShow(true)}>Create New Batch</button></div>{error&&<div className="error-message">{error}</div>}
 <div style={{overflowX:'auto'}}><table className="data-table"><thead><tr><th>Batch Number</th><th>Oil Type</th><th>Product</th><th>Qty</th><th>Oil Consumed</th><th>Status</th><th>Date</th></tr></thead><tbody>{rows.map(r=><tr key={r._id}><td>{r.batchNumber}</td><td>{r.oilType}</td><td>{r.productLabel||r.packagingType}</td><td>{r.quantity}</td><td>{n(r.oilConsumed?.quantity).toFixed(2)} {r.oilConsumed?.unit||''}</td><td>{r.status}</td><td>{r.createdAt?new Date(r.createdAt).toLocaleDateString():'-'}</td></tr>)}</tbody></table></div>
 {show&&<div className="modal"><div className="modal-content"><div className="modal-header"><h3>Create Oil Batch</h3><button className="modal-close" onClick={()=>setShow(false)}>×</button></div><p className="help-text">Batch Number comes from Oil Purchase and stays active until that tanker lot is exhausted.</p><div className="form-grid">
 <div className="form-group"><label>Oil Type *</label><select value={form.oilType} onChange={e=>setForm({...form,oilType:e.target.value,batchNumber:'',productTypeId:'',quantity:0})}><option value="">-- Select --</option>{(opts.oilTypes||[]).map((x:any)=><option key={x.oilType} value={x.oilType}>{x.oilType} ({n(x.availableQuantity).toFixed(2)} available)</option>)}</select></div>
 <div className="form-group"><label>Batch Number *</label><select value={form.batchNumber} onChange={e=>setForm({...form,batchNumber:e.target.value,quantity:0})} disabled={!form.oilType}><option value="">-- Select --</option>{batches.map((x:any)=><option key={x._id} value={x.batchNumber}>{x.batchNumber} — {n(x.availableQuantity).toFixed(2)} {x.inventoryUnit}</option>)}</select></div>
 <div className="form-group"><label>Product Type *</label><select value={form.productTypeId} onChange={e=>setForm({...form,productTypeId:e.target.value,quantity:0})} disabled={!form.oilType}><option value="">-- Select --</option>{products.map((x:any)=><option key={x._id} value={x._id}>{x.label}</option>)}</select></div>
 <div className="form-group"><label>Quantity *</label><input type="number" min="1" max={cap?.calculatedMaxQuantity||undefined} value={form.quantity} onChange={e=>setForm({...form,quantity:n(e.target.value)})}/>{cap&&<small style={{marginTop:6,color:'#5b6770'}}>Available to Produce: <b>{cap.calculatedMaxQuantity}</b> units (Oil limit {cap.rawOilLimit}, Packaging limit {cap.packagingLimit})</small>}</div>
 </div><div className="modal-actions"><button className="primary-button" disabled={loading||!cap||n(cap.calculatedMaxQuantity)<=0} onClick={create}>{loading?'Creating...':'Create Batch'}</button><button className="secondary-button" onClick={()=>setShow(false)}>Cancel</button></div></div></div>}
 </div>;
};export default OilBatchProcessing;
