import React, { useEffect, useState } from 'react';
import api from '../services/api';
import { settingsApi } from '../services/businessApi';
import './Pages.css';

type Tab='company'|'packaging'|'polythene'|'oil'|'maintenance'|'dashboard';
const id=()=>`${Date.now()}-${Math.floor(Math.random()*10000)}`;
const deep=(v:any)=>JSON.parse(JSON.stringify(v));

const Settings:React.FC=()=>{
  const [tab,setTab]=useState<Tab>('company');
  const [settings,setSettings]=useState<any>(null);
  const [saving,setSaving]=useState(false);
  const [msg,setMsg]=useState('');
  const load=async()=>{const r=await settingsApi.get();setSettings(r.data.data);};
  useEffect(()=>{load();},[]);
  const save=async()=>{setSaving(true);setMsg('');try{const r=await settingsApi.update(settings);setSettings(r.data.data);setMsg('Settings saved successfully.');}catch(e:any){setMsg(e?.error?.message||e?.message||'Failed to save settings');}finally{setSaving(false);}};
  if(!settings)return <div className="page-loading">Loading settings...</div>;
  const patchCompany=(path:string,value:any)=>{const next=deep(settings);const keys=path.split('.');let cur=next.company;for(let i=0;i<keys.length-1;i++){cur[keys[i]]=cur[keys[i]]||{};cur=cur[keys[i]];}cur[keys[keys.length-1]]=value;setSettings(next);};
  const addPackaging=()=>setSettings({...settings,packagingTypes:[...(settings.packagingTypes||[]),{id:`PKG_${id()}`,code:'NEW_PACKAGING',label:'New Packaging',category:'PRIMARY',purchaseUnit:'PCS',inventoryUnit:'PCS',hasSubtypes:false,batchProcessingVisible:true,active:true,sortOrder:(settings.packagingTypes?.length||0)*10+10}]});
  const addPoly=()=>setSettings({...settings,polytheneSubtypes:[...(settings.polytheneSubtypes||[]),{id:`POLY_${id()}`,code:`POLY_${id()}`,label:'470G',containerType:'PACKET',parentPackagingCode:'POLYTHENE_BUNDLE',size:{value:470,unit:'GRAM'},finishedProductLabel:'470g Packet',unitsPerBundle:1,oilConsumptionPerUnit:{quantity:.47,unit:'KG'},active:true,batchProcessingVisible:true,purchaseDropdownVisible:true,sortOrder:(settings.polytheneSubtypes?.length||0)*10+10}]});
  const addOil=()=>setSettings({...settings,oilTypes:[...(settings.oilTypes||[]),{id:`OIL_${id()}`,code:'NEW_OIL',label:'New Oil',baseInventoryUnit:'KG',densityKgPerLiter:0.91,hsnCode:'',active:true,sortOrder:(settings.oilTypes?.length||0)*10+10}]});
  const tabs:[Tab,string][]=[['company','Company Details'],['packaging','Packaging Types'],['polythene','Polythene Subtypes'],['oil','Oil Types'],['maintenance','Maintenance'],['dashboard','Dashboard Tiles']];
  return <div className="module-page">
    <div className="module-header"><div><h1>Application Settings</h1><p>Configure business masters and application behavior</p></div><button className="primary-button" onClick={save} disabled={saving}>{saving?'Saving...':'Save Settings'}</button></div>
    {msg&&<div className={msg.includes('success')?'success-message':'error-message'}>{msg}</div>}
    <div className="tabs" style={{marginBottom:16}}>{tabs.map(([k,l])=><button key={k} className={`tab-button ${tab===k?'active':''}`} onClick={()=>setTab(k)}>{l}</button>)}</div>

    {tab==='company'&&<div className="section"><h2>Owner / Company Details</h2><div className="form-grid">
      {[
        ['companyName','Company Name'],['tax.gstNumber','GST Number'],['tax.panNumber','PAN'],['tax.tanNumber','TAN'],['tax.fssaiNumber','FSSAI Number'],
        ['address.line1','Address Line 1'],['address.line2','Address Line 2'],['address.city','City'],['address.district','District'],['address.state','State'],['address.stateCode','State Code'],['address.pinCode','PIN Code'],
        ['contact.phone','Phone'],['contact.alternatePhone','Alternate Phone'],['contact.email','Email'],['bank.bankName','Bank Name'],['bank.accountHolderName','Account Holder'],['bank.accountNumber','Account Number'],['bank.ifscCode','IFSC'],['bank.branchName','Branch'],['payment.upiId','UPI ID'],['payment.gpayNumber','GPay'],['payment.phonePeNumber','PhonePe']
      ].map(([p,l])=>{const v=p.split('.').reduce((o:any,k)=>o?.[k],settings.company)||'';return <div className="form-group" key={p}><label>{l}</label><input value={v} onChange={e=>patchCompany(p,e.target.value)}/></div>})}
      <div className="form-group" style={{gridColumn:'1 / -1'}}><label>Terms & Conditions (one per line)</label><textarea rows={5} value={(settings.company?.invoice?.termsAndConditions||[]).join('\n')} onChange={e=>patchCompany('invoice.termsAndConditions',e.target.value.split('\n').filter(Boolean))}/></div>
      <div className="form-group"><label>Company Logo</label><input type="file" accept="image/png,image/jpeg" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;const fd=new FormData();fd.append('logo',f);const r=await api.post('/settings/company/logo',fd,{headers:{'Content-Type':'multipart/form-data'}});patchCompany('branding.logoUrl',r.data.data.logoUrl);}}/>{settings.company?.branding?.logoUrl&&<small>{settings.company.branding.logoUrl}</small>}</div>
    </div></div>}

    {tab==='packaging'&&<div className="section"><div style={{display:'flex',justifyContent:'space-between'}}><h2>Packaging Types</h2><button className="primary-button" onClick={addPackaging}>+ Add Type</button></div><div className="table-wrapper"><table className="data-table"><thead><tr><th>Code</th><th>Label</th><th>Category</th><th>Purchase Unit</th><th>Inventory Unit</th><th>Subtypes</th><th>Batch Visible</th><th>Active</th></tr></thead><tbody>{(settings.packagingTypes||[]).map((p:any,i:number)=><tr key={p.id}><td><input value={p.code} onChange={e=>{const x=deep(settings);x.packagingTypes[i].code=e.target.value;setSettings(x)}}/></td><td><input value={p.label} onChange={e=>{const x=deep(settings);x.packagingTypes[i].label=e.target.value;setSettings(x)}}/></td><td><select value={p.category} onChange={e=>{const x=deep(settings);x.packagingTypes[i].category=e.target.value;setSettings(x)}}><option>PRIMARY</option><option>SECONDARY</option></select></td><td><select value={p.purchaseUnit} onChange={e=>{const x=deep(settings);x.packagingTypes[i].purchaseUnit=e.target.value;setSettings(x)}}>{['PCS','BUNDLE','KG','METER'].map(v=><option key={v}>{v}</option>)}</select></td><td><select value={p.inventoryUnit} onChange={e=>{const x=deep(settings);x.packagingTypes[i].inventoryUnit=e.target.value;setSettings(x)}}>{['PCS','POUCH','KG','METER'].map(v=><option key={v}>{v}</option>)}</select></td><td><input type="checkbox" checked={!!p.hasSubtypes} onChange={e=>{const x=deep(settings);x.packagingTypes[i].hasSubtypes=e.target.checked;setSettings(x)}}/></td><td><input type="checkbox" checked={!!p.batchProcessingVisible} onChange={e=>{const x=deep(settings);x.packagingTypes[i].batchProcessingVisible=e.target.checked;setSettings(x)}}/></td><td><input type="checkbox" checked={!!p.active} onChange={e=>{const x=deep(settings);x.packagingTypes[i].active=e.target.checked;setSettings(x)}}/></td></tr>)}</tbody></table></div>
      <h3 style={{marginTop:24}}>Packaging Variants (Can / PP Box)</h3><div className="table-wrapper"><table className="data-table"><thead><tr><th>Parent</th><th>Code</th><th>Label</th><th>Capacity</th><th>Active</th></tr></thead><tbody>{(settings.packagingSubtypes||[]).map((p:any,i:number)=><tr key={p.id}><td>{p.parentPackagingCode}</td><td><input value={p.code} onChange={e=>{const x=deep(settings);x.packagingSubtypes[i].code=e.target.value;setSettings(x)}}/></td><td><input value={p.label} onChange={e=>{const x=deep(settings);x.packagingSubtypes[i].label=e.target.value;setSettings(x)}}/></td><td><input type="number" value={p.capacity||''} onChange={e=>{const x=deep(settings);x.packagingSubtypes[i].capacity=Number(e.target.value);setSettings(x)}}/></td><td><input type="checkbox" checked={!!p.active} onChange={e=>{const x=deep(settings);x.packagingSubtypes[i].active=e.target.checked;setSettings(x)}}/></td></tr>)}</tbody></table></div>
    </div>}

    {tab==='polythene'&&<div className="section"><div style={{display:'flex',justifyContent:'space-between'}}><div><h2>Polythene Bundle Subtypes</h2><p>Configure new sizes such as 470g Packet or 410g Bottle without code changes.</p></div><button className="primary-button" onClick={addPoly}>+ Add Subtype</button></div><div className="table-wrapper"><table className="data-table"><thead><tr><th>Code</th><th>Label</th><th>Container</th><th>Finished Product</th><th>Size</th><th>Unit</th><th>Units / Bundle</th><th>Oil Qty</th><th>Oil Unit</th><th>Active</th></tr></thead><tbody>{(settings.polytheneSubtypes||[]).map((p:any,i:number)=><tr key={p.id}><td><input value={p.code} onChange={e=>{const x=deep(settings);x.polytheneSubtypes[i].code=e.target.value;setSettings(x)}}/></td><td><input value={p.label} onChange={e=>{const x=deep(settings);x.polytheneSubtypes[i].label=e.target.value;setSettings(x)}}/></td><td><select value={p.containerType||'PACKET'} onChange={e=>{const x=deep(settings);x.polytheneSubtypes[i].containerType=e.target.value;setSettings(x)}}><option>PACKET</option><option>POUCH</option><option>BOTTLE</option></select></td><td><input value={p.finishedProductLabel} onChange={e=>{const x=deep(settings);x.polytheneSubtypes[i].finishedProductLabel=e.target.value;setSettings(x)}}/></td><td><input type="number" value={p.size?.value||0} onChange={e=>{const x=deep(settings);x.polytheneSubtypes[i].size.value=Number(e.target.value);setSettings(x)}}/></td><td><select value={p.size?.unit} onChange={e=>{const x=deep(settings);x.polytheneSubtypes[i].size.unit=e.target.value;setSettings(x)}}>{['LITER','ML','GRAM','KG'].map(v=><option key={v}>{v}</option>)}</select></td><td><input type="number" min="1" value={p.unitsPerBundle||0} onChange={e=>{const x=deep(settings);x.polytheneSubtypes[i].unitsPerBundle=Number(e.target.value);setSettings(x)}}/></td><td><input type="number" step="0.001" value={p.oilConsumptionPerUnit?.quantity||0} onChange={e=>{const x=deep(settings);x.polytheneSubtypes[i].oilConsumptionPerUnit.quantity=Number(e.target.value);setSettings(x)}}/></td><td><select value={p.oilConsumptionPerUnit?.unit||'KG'} onChange={e=>{const x=deep(settings);x.polytheneSubtypes[i].oilConsumptionPerUnit.unit=e.target.value;setSettings(x)}}><option>KG</option><option>LITER</option></select></td><td><input type="checkbox" checked={!!p.active} onChange={e=>{const x=deep(settings);x.polytheneSubtypes[i].active=e.target.checked;setSettings(x)}}/></td></tr>)}</tbody></table></div></div>}

    {tab==='oil'&&<div className="section"><div style={{display:'flex',justifyContent:'space-between'}}><h2>Oil Types</h2><button className="primary-button" onClick={addOil}>+ Add Oil Type</button></div><div className="table-wrapper"><table className="data-table"><thead><tr><th>Code</th><th>Label</th><th>Inventory Unit</th><th>Density KG/L</th><th>HSN</th><th>Active</th></tr></thead><tbody>{(settings.oilTypes||[]).map((o:any,i:number)=><tr key={o.id}><td><input value={o.code} onChange={e=>{const x=deep(settings);x.oilTypes[i].code=e.target.value;setSettings(x)}}/></td><td><input value={o.label} onChange={e=>{const x=deep(settings);x.oilTypes[i].label=e.target.value;setSettings(x)}}/></td><td><select value={o.baseInventoryUnit} onChange={e=>{const x=deep(settings);x.oilTypes[i].baseInventoryUnit=e.target.value;setSettings(x)}}><option>KG</option><option>LITER</option></select></td><td><input type="number" step="0.001" value={o.densityKgPerLiter||''} onChange={e=>{const x=deep(settings);x.oilTypes[i].densityKgPerLiter=Number(e.target.value);setSettings(x)}}/></td><td><input value={o.hsnCode||''} onChange={e=>{const x=deep(settings);x.oilTypes[i].hsnCode=e.target.value;setSettings(x)}}/></td><td><input type="checkbox" checked={!!o.active} onChange={e=>{const x=deep(settings);x.oilTypes[i].active=e.target.checked;setSettings(x)}}/></td></tr>)}</tbody></table></div></div>}

    {tab==='maintenance'&&<div className="section"><h2>Maintenance Types & Subtypes</h2>{(settings.maintenanceTypes||[]).map((t:any,ti:number)=><div key={t.id} style={{border:'1px solid #e1e5ea',borderRadius:8,padding:14,marginBottom:14}}><div style={{display:'flex',gap:12,alignItems:'center'}}><strong>{t.label}</strong><code>{t.code}</code><label><input type="checkbox" checked={!!t.active} onChange={e=>{const x=deep(settings);x.maintenanceTypes[ti].active=e.target.checked;setSettings(x)}}/> Active</label><button className="secondary-button" style={{padding:'5px 10px'}} onClick={()=>{const x=deep(settings);x.maintenanceTypes[ti].subtypes.push({id:`SUB_${id()}`,code:'NEW_SUBTYPE',label:'New Subtype',entryBehavior:'GENERAL_EXPENSE',inventoryType:'NONE',stockAction:'NO_STOCK_CHANGE',quantityRequired:false,amountRequired:true,attachmentAllowed:true,active:true,sortOrder:100});setSettings(x)}}>+ Subtype</button></div><table className="data-table" style={{marginTop:10}}><thead><tr><th>Code</th><th>Label</th><th>Behavior</th><th>Inventory</th><th>Action</th><th>Qty?</th><th>Amount?</th><th>Active</th></tr></thead><tbody>{(t.subtypes||[]).map((s:any,si:number)=><tr key={s.id}><td><input value={s.code} onChange={e=>{const x=deep(settings);x.maintenanceTypes[ti].subtypes[si].code=e.target.value;setSettings(x)}}/></td><td><input value={s.label} onChange={e=>{const x=deep(settings);x.maintenanceTypes[ti].subtypes[si].label=e.target.value;setSettings(x)}}/></td><td><select value={s.entryBehavior} onChange={e=>{const x=deep(settings);x.maintenanceTypes[ti].subtypes[si].entryBehavior=e.target.value;setSettings(x)}}>{['INVENTORY_ADJUSTMENT','GENERAL_EXPENSE','INVENTORY_AND_EXPENSE','INFORMATION_ONLY'].map(v=><option key={v}>{v}</option>)}</select></td><td><select value={s.inventoryType} onChange={e=>{const x=deep(settings);x.maintenanceTypes[ti].subtypes[si].inventoryType=e.target.value;setSettings(x)}}>{['RAW_OIL','PACKAGING','FINISHED_GOOD','NONE'].map(v=><option key={v}>{v}</option>)}</select></td><td><select value={s.stockAction} onChange={e=>{const x=deep(settings);x.maintenanceTypes[ti].subtypes[si].stockAction=e.target.value;setSettings(x)}}>{['REDUCE','ADD','QUARANTINE','NO_STOCK_CHANGE'].map(v=><option key={v}>{v}</option>)}</select></td><td><input type="checkbox" checked={!!s.quantityRequired} onChange={e=>{const x=deep(settings);x.maintenanceTypes[ti].subtypes[si].quantityRequired=e.target.checked;setSettings(x)}}/></td><td><input type="checkbox" checked={!!s.amountRequired} onChange={e=>{const x=deep(settings);x.maintenanceTypes[ti].subtypes[si].amountRequired=e.target.checked;setSettings(x)}}/></td><td><input type="checkbox" checked={!!s.active} onChange={e=>{const x=deep(settings);x.maintenanceTypes[ti].subtypes[si].active=e.target.checked;setSettings(x)}}/></td></tr>)}</tbody></table></div>)}</div>}

    {tab==='dashboard'&&<div className="section"><h2>Dashboard Tiles</h2><table className="data-table"><thead><tr><th>Tile</th><th>Module</th><th>Visible</th><th>Sort Order</th><th>Active</th></tr></thead><tbody>{(settings.dashboardTiles||[]).map((t:any,i:number)=><tr key={t.id}><td>{t.label}</td><td>{t.module}</td><td><input type="checkbox" checked={!!t.visible} onChange={e=>{const x=deep(settings);x.dashboardTiles[i].visible=e.target.checked;setSettings(x)}}/></td><td><input type="number" value={t.sortOrder||0} onChange={e=>{const x=deep(settings);x.dashboardTiles[i].sortOrder=Number(e.target.value);setSettings(x)}}/></td><td><input type="checkbox" checked={!!t.active} onChange={e=>{const x=deep(settings);x.dashboardTiles[i].active=e.target.checked;setSettings(x)}}/></td></tr>)}</tbody></table></div>}
  </div>;
};
export default Settings;
